### ISSUE TITLE
Configurable icons for hits

### ISSUE THREAD

**Issue by merced317** [ralphbean/narcissus#8]
It would be great to have the icons that appear on the map be representative of the link that is being accessed.  Sunglasses appear if the link is for InstantCSI, CentOS logo appears for the centos folder, etc.

**Comment by ralphbean** [comment]
This should probably be configurable in /etc/narcissus.conf

**Comment by paulmezz** [comment]
Well why haven't you done it yet?  :D

**Comment by ralphbean** [comment]
Gonna close this as `WONTFIX`.  Sorry guys!
